### ISSUE TITLE
Invalid upstream response (403)

### ISSUE THREAD

**Issue by Mark-Shun** [kawarimidoll/typograssy#61]
Hello, I quite like this feature for the README file and implemented it like last week, but it seems to not work at the moment.

When clicking on my embed in my README I get: Invalid upstream response (403)
Has the requests quota been reached for Deno?
Resulting in the typograssy embed not being able to connect anymore?

![image](https://github.com/kawarimidoll/typograssy/assets/57092443/f7183c2a-55b5-4f29-8f73-2123d4f58703)

**Comment by Epsilon-Alpha** [comment]
Yes, the quote has been exceeded, evident on the [homepage](https://typograssy.deno.dev/)
It stopped working for me as well.
![image](https://github.com/kawarimidoll/typograssy/assets/16699968/2f95a387-23ac-4c3a-a894-46f09f1e89a3)

**Comment by Mark-Shun** [comment]
Seems to be working again 👍
